apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-new
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  labels:
    app: postgres
    type: local
spec:
  storageClassName: standard  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/postgres-data