apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
type: Opaque
data:
  POSTGRES_USER: dXNlcg==          # "user"
  POSTGRES_PASSWORD: cGFzcw==      # "pass"
  POSTGRES_DB: cGV0Y2xpbmlj        # "petclinic"
