apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.name" .}}-config
  labels:
    app: {{ include "mychart.name" .}}
data:
  POSTGRES_DB: {{ .Values.postgres.dbName}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.name" .}}-init-scripts
  labels:
    app: {{ include "mychart.name" .}}
data:
  01-schema.sql: |
  {{ .File.Get "sql/01-schema.sql" | indent 4 }}    
  02-data.sql: |
  {{ .File.Get "sql/02-data.sql" | indent 4 }}
