apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.name" .}}-deployment
spec: 
  replicas: {{ .Values.replicasCount}}
  selector:
    matchLabels:
      app: {{ include "mychart.name" .}}
  template:
    metadata: 
      labels:
        app: {{ include "mychart.name" .}}
    spec:
      containers: 
        - name: {{ .Values.image.repository}}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "mychart.name" .}}-secret
            - configMapRef:
                name: {{ include "mychart.name" .}}-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-scripts