apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.name" .}}-pv
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  labels:
    app: {{include "mychart.name" .}}
    type: local
spec:
  storageClassName: {{ .Values.pv.storageClassName }}  
  capacity:
    storage: {{ .Values.pv.capacity}}
  accessModes:
    - {{ .Values.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.persistentVolumeReclaimPolicy }}
  hostPath:
    path: {{ .Values.pv.hostPath }}