apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.name" .}}-pvc
  labels:
    app: {{include "mychart.name" .}}
spec: 
  storageClassName: {{ .Values.pvc.storageClassName}}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
