apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.name" .}}-secret
  labels:
    app: {{ include "mychart.name" .}}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER}}        
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD}}     
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB}}      
